name: E2e test

on: [push, pull_request]

jobs:
  run-e2e-test:
    strategy:
      matrix:
        version: [16, 18]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          node-version: ${{ matrix.version  }}
      - name: Install berry
        run: corepack enable

      - name: install dependices
        run: yarn
      
      - name: run e2e test
        run: yarn e2e
